# Use an official Python runtime as a parent image
FROM python:3.11-slim

WORKDIR /app

COPY docker/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/

WORKDIR /app/src

EXPOSE 8000

# Set PYTHONPATH so Python can find "src.api"
ENV PYTHONPATH=/app

CMD python /app/src/wait_for_mlflow.py && uvicorn src.api:app --host 0.0.0.0 --port 8000
