FROM python:3.9.16-slim

WORKDIR /mlops

RUN pip install mlflow==2.20.2

ENV BACKEND_URI sqlite:///mlflow.db

EXPOSE 5000

CMD mlflow server --backend-store-uri $BACKEND_URI --host 0.0.0.0 --port 5000