version: '3.8'

networks:
  internal:
    driver: bridge

services:
  mlflow_server:
    restart: always
    build:
      context: docker/mlflow
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    networks:
      - internal
    image: mlflow_server
    ports:
      - "5050:5050"

  train_flow:
    build:
      context: .
      dockerfile: docker/train_flow/Dockerfile.train_flow
    container_name: train_flow
    networks:
      - internal
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow_server:5050"
      PREFECT_API_URL: "http://prefect_server_ui:4200/api"
    # volumes:
    #   - ./src:/app/src
    #   - ./data:/app/data
    depends_on:
      - mlflow_server
      - prefect_server_ui
    ports:
      - "9696:9696"

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.api
    container_name: api
    networks:
      - internal
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow_server:5050"
    depends_on:
      - mlflow_server
      - train_flow
    ports:
      - "8000:8000"

  prefect_server_ui:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect_server_ui
    networks:
      - internal
    environment:
      PREFECT_HOME: /data
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"  # Prefect server UI and API
    volumes:
      - prefect-data:/data  # Persistent storage
      - .:/app  # Mount current directory

  drift_detection:
    build:
      context: .
      dockerfile: docker/drift_detection/Dockerfile.drift
    container_name: drift_detection
    networks:
      - internal
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow_server:5050"
      PREFECT_API_URL: "http://prefect_server_ui:4200/api"
    depends_on:
      - mlflow_server
      - prefect_server_ui
      - train_flow
      - api
    ports:
      - "9090:9090"

volumes:
  prefect-data: {}